const communityData = [
  {
    id: "tech-enthusiasts",
    name: "Tech Enthusiasts",
    info: "A community for tech lovers to discuss the latest trends, gadgets, and innovations.",
    admin: "John Doe",
    picture: "https://via.placeholder.com/150",
    members: 1200,
    tags: ["Technology", "Innovation", "Gadgets"],
  },
  {
    id: "fitness-freaks",
    name: "Fitness Freaks",
    info: "Join us to share fitness tips, workout routines, and healthy lifestyle ideas.",
    admin: "Jane Smith",
    picture: "https://via.placeholder.com/150",
    members: 850,
    tags: ["Fitness", "Health", "Wellness"],
  },
  {
    id: "foodies-united",
    name: "Foodies United",
    info: "A paradise for food lovers to explore recipes, restaurants, and culinary adventures.",
    admin: "Emily Brown",
    picture: "https://via.placeholder.com/150",
    members: 950,
    tags: ["Food", "Cooking", "Recipes"],
  },
  {
    name: "Travel Diaries",
    info: "Share your travel experiences, tips, and bucket lists with fellow wanderers.",
    admin: "Michael Green",
    picture: "https://via.placeholder.com/150",
    members: 1100,
    tags: ["Travel", "Adventure", "Exploration"],
  },
  {
    name: "Art & Creativity",
    info: "A space for artists and creatives to showcase their work and inspire others.",
    admin: "Sophia Wilson",
    picture: "https://via.placeholder.com/150",
    members: 700,
    tags: ["Art", "Creativity", "Design"],
  },
  {
    name: "Cricket Fanatics",
    info: "A community for cricket lovers to discuss matches, players, and strategies.",
    admin: "Rahul Sharma",
    picture: "https://via.placeholder.com/150",
    members: 1500,
    tags: ["Cricket", "Sports", "Fans"],
  },
  {
    name: "Badminton Champs",
    info: "Join us to share badminton tips, tournaments, and training routines.",
    admin: "Anjali Verma",
    picture: "https://via.placeholder.com/150",
    members: 900,
    tags: ["Badminton", "Sports", "Fitness"],
  },
  {
    name: "Music Lovers",
    info: "A place for music enthusiasts to share playlists, discuss genres, and jam together.",
    admin: "Chris Martin",
    picture: "https://via.placeholder.com/150",
    members: 2000,
    tags: ["Music", "Instruments", "Genres"],
  },
  {
    name: "Guitar Heroes",
    info: "A community for guitar players to share tips, techniques, and performances.",
    admin: "Alex Johnson",
    picture: "https://via.placeholder.com/150",
    members: 750,
    tags: ["Music", "Guitar", "Instruments"],
  },
  {
    name: "Classical Beats",
    info: "Explore the world of classical music and connect with fellow enthusiasts.",
    admin: "Sophia Lee",
    picture: "https://via.placeholder.com/150",
    members: 600,
    tags: ["Music", "Classical", "Culture"],
  },
];

export default communityData;
